version: '3'

services:
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    

  wordpress:
    depends_on:
      - db
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$wp_user_name
      - WORDPRESS_DB_PASSWORD=$wp_user_pass
      - WORDPRESS_DB_NAME=wordpress
      ports:
      - 8085:80
    volumes:
      - wordpress:/var/www/html
